library(dplyr)
data2 <- read.table("household_power_consumption.txt",sep=";",header=TRUE,na.strings="?",)
data2 <- data2 %>% filter(Date %in% c("1/2/2007","2/2/2007"))
datetime <- strptime(paste(data2$Date, data2$Time, sep=" "), "%d/%m/%Y %H:%M:%S")
png(filename="Plot3.png",width=400,height=400)
plot(datetime,data2$Sub_metering_1,type="n",xlab="",ylab="Energy sub metering")
with(data2,lines(datetime,Sub_metering_1))
with(data2,lines(datetime,Sub_metering_2,col="red"))
with(data2,lines(datetime,Sub_metering_3,col="blue"))
legend("topright",lty=1,col=c("black","red","blue"),legend=c("Sub_metering_1","Sub_metering_2","Sub_metering_3"))
dev.off()